Vagrant.configure("2") do |config|
    # VM 1
    config.vm.define "openmoondev" do |openmoondev|
        # Pull official Debian Image
        openmoondev.vm.box = "debian/bullseye64"

        # Give real ip address
        openmoondev.vm.network "private_network", ip: "10.1.10.2"
        openmoondev.vm.hostname = "openmoondev"

        # Bind to non-root ports if needed
        #openmoondev.vm.network "forwarded_port", guest: 80, host: 8080,
            #auto_correct: true

        # Sync folder to repo home
        config.vm.synced_folder "src/", "/home/vagrant/src"

        # Virtualbox settings
        openmoondev.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.memory = 2048
            vb.cpus = 2
            vb.name = "openmoondev-vagrant"
        end

        # Post installation scripts
        openmoondev.vm.provision "shell", path: "vagrant-config.sh"
    end
end
